const BUTTON_RADIUS = 28;
const BORDER_RADIUS = 8;
const ACTIVE_COLOR = '#EB5757';
const INACTIVE_COLOR = '#CFD8DC';
const REGULAR_FONT = 'IBMPlexSans';
const MEDIUM_FONT = 'IBMPlexSans-Medium';

export {BUTTON_RADIUS, BORDER_RADIUS, ACTIVE_COLOR, INACTIVE_COLOR, REGULAR_FONT, MEDIUM_FONT}
